spring.application.name=assignment
server.port = 8080

# Gemini API Configuration
gemini.api.key=${GEMINI_API_KEY:AIzaSyBeIblNaZooOovWkU4LqEvMxrtTBonVNy0}
gemini.model.name=gemini-2.0-flash


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
